### ISSUE TITLE
Craft 3 version of Search Plus

### ISSUE THREAD

**Issue by jamesmacwhite** [TopShelfCraft/Search-Plus#1]
Hi @michaelrog.

Just wondering if there's any news on the development of the Craft 3 version of Search Plus? I noticed that Craftnet originally stated "Currently in development" but then switched back to "Not available yet" in terms of the Craft 3 plugin status. I am currently working on migrating a Craft 2 project which uses Search Plus for data mapping and it would of course be ideal if this could be used under Craft 3, given we've already built our data mapping logic around it. There will be the requirement to port this anyway, but given we've already built some custom data mappings, it will be an easier task continuing under Search Plus

Thanks in advance!

**Comment by jamesmacwhite** [comment]
I don't think this is going to be ported, but for anyone else that may have a Craft 2 project using this, an alternative under Craft 3 is https://github.com/riasvdv/craft-scout

**Comment by michaelrog** [comment]
Howdy James — yes, a Craft 3 version is in the works.
